## UniFlex Agent config file

config:
  name: 'HC node'
  info: 'filter runs on local node'
  iface: 'lo'
  iface: 'lo'
  sub: "tcp://192.168.10.157:8990"
  pub: "tcp://192.168.10.157:8989"

broker:
  xpub: "tcp://192.168.10.157:8990"
  xsub: "tcp://192.168.10.157:8989"

control_applications:
  myFilter:
      file : my_filter.py
      class_name : MyAvgFilter
      kwargs : {"window": 5}

  discovery:
      module : uniflex_app_discovery_pyre
      class_name : PyreDiscoverySlaveModule
      kwargs: {"iface":"lo", "groupName":"uniflex_1234"}

modules:
  simple:
      module : uniflex_module_wifi
      class_name : WifiModule
      devices : ['phy0']
      kwargs : {}

